exception: Unwrap InvocationTargetException to record the cause
When putting the exception in the Reporter, unwrap
InvocationTargetExceptions to report the underlying cause. Also if trace,
log the exception as info level.

Fixes https://github.com/bndtools/bnd/issues/1601

Signed-off-by: BJ Hargrave <bj@bjhargrave.com>