fix NoClassDefFoundError
fixes regression of recent Eclipse-2023-12 PR Exception: java.lang.NoClassDefFoundError: org/slf4j/impl/SimpleLogger
	at aQute.bnd.main.bnd.doLogging(bnd.java:487)

Signed-off-by: Christoph Rueger <chrisrueger@gmail.com>