fix two failing tests
CorruptManifest > testCorruptJar() FAILED
    org.opentest4j.AssertionFailedError: expected: <. . > but was: <. .>
        at app//org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
        at app//org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
        at app//org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
        at app//org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:182)
        at app//org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:177)
        at app//org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:1142)
        at app//test.CorruptManifest.testCorruptJar(CorruptManifest.java:59)

MultiReleaseTest > testBuild() FAILED
    org.opentest4j.AssertionFailedError:
    expected: ""
     but was: "Require-Capability: osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=9))""
        at java.base@17.0.11/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base@17.0.11/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
        at java.base@17.0.11/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base@17.0.11/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at app//test.MultiReleaseTest.testBuild(MultiReleaseTest.java:96)

Signed-off-by: Christoph Rueger <chrisrueger@gmail.com>

check null

Signed-off-by: Christoph Rueger <chrisrueger@gmail.com>