exception: Log debug any reported exceptions
This will allow the complete exception to be seen in gradle or maven
output when --debug is used.

Signed-off-by: BJ Hargrave <bj@bjhargrave.com>