exception: Handle reporting exceptions better
Use Throwable.toString instead of Throwable.getMessage which can be
empty or null. Use Reporter.exception instead of Reporter.error.

Signed-off-by: BJ Hargrave <bj@bjhargrave.com>