Remove usage of internal class RenamePackageProcessor
Signed-off-by: Christoph Rueger <chrisrueger@gmail.com>

Remove usage of internal class RenamePackageProcessor

* fixes #5891
* this fixes the NoClassDefFoundError: org/eclipse/jdt/internal/corext/refactoring/rename/RenamePackageProcessor because RenamePackageProcessor seems to be internal
* we loose a tiny bit of detail in the Rename dialog method

Signed-off-by: Christoph Rueger <chrisrueger@gmail.com>