[junit] A previous patch let JUnit 4 handle all the testcases. However, this causes some difficulties because now the testcases had a facade. I.e. could not set the Bundle Context any longer. Now if a test case extends TestCase (that is, JUnit 3) it will use the JUNit 3 runner.
java.lang.NoSuchMethodException: junit.framework.JUnit4TestCaseFacade.setBundleContext(org.osgi.framework.BundleContext)
	at java.lang.Class.getMethod(Class.java:1773)
	at aQute.junit.BasicTestReport.startTest(BasicTestReport.java:61)